services:
  # ######################################################
  # FRONTEND #############################################
  # ######################################################
  frontend:
    # name the image so that it cannot be found in a DockerHub repository, otherwise it will not be built locally from the 'dockerfile' but pulled from there
    image: webcraftmedia/jahrweiser:local-development
    build:
      target: development
    environment:
      - NODE_ENV="development"
      - PORT=3000
      # - DEBUG=true
    ports:
      - 3000:3000
    volumes:
      # This makes sure the docker container has its own node modules.
      # Therefore it is possible to have a different node version on the host machine
      # - frontend_node_modules:/app/node_modules
      #- frontend_dot_nuxt:/app/.nuxt
      # bind the local folder to the docker to allow live reload
      - ./frontend:/app

#volumes:
#  frontend_node_modules:
#  frontend_dot_nuxt: