name: "test:build test docker"

on: push

jobs:
  # only (but most important) job from this workflow required for pull requests
  # check results serve as run conditions for all other jobs here
  files-changed:
    name: Detect File Changes - test-build-docker
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.filter }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7

      - name: Check for file changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            filter:
              - '**/*'
              - '.github/workflows/*'
          list-files: shell

  build-production:
    if: needs.files-changed.outputs.changes == 'true'
    name: Build Docker Production
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7

      - name: Env File
        run: cp frontend/.env.example frontend/.env
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Build Docker Production
        run: docker compose -f docker-compose.yml build
        working-directory: ${{env.WORKING_DIRECTORY}}

  build-development:
    if: needs.files-changed.outputs.changes == 'true'
    name: Build Docker Development
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7

      - name: Env File
        run: cp frontend/.env.example frontend/.env
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Build Docker Development
        run: docker compose build
        working-directory: ${{env.WORKING_DIRECTORY}}