name: "frontend:test:build test code"

on: push

jobs:
  # only (but most important) job from this workflow required for pull requests
  # check results serve as run conditions for all other jobs here
  files-changed:
    name: Detect File Changes - frontend-test-build-code
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.filter }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7

      - name: Check for frontend file changes
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          token: ${{ github.token }}
          filters: |
            filter:
              - 'frontend/**/*'
              - '.github/workflows/*'
          list-files: shell

  build:
    if: needs.files-changed.outputs.changes == 'true'
    name: Build - Frontend
    needs: files-changed
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: ./frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7

      - name: Env File
        run: cp .env.example .env
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Frontend | Build
        run: npm install && npm run build
        working-directory: ${{env.WORKING_DIRECTORY}}

      - name: Frontend | Size Check
        run: npm run test:size
        working-directory: ${{env.WORKING_DIRECTORY}}